SOCIAL_AUTH_TWITTER_KEY = 'gtAuPM2P4Xe5iqw5h0z4ZhmtY'
SOCIAL_AUTH_TWITTER_SECRET = 'v5EMSTBikvQv2xS5wBHWqlCBt4oz7VmmVPqDs1Q8mDRuK6cA7g'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'