version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker build Fall2017Swe573:$CIRCLE_BRANCH
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - run:
          name: Run tests
          command: |
            docker-compose -f ./docker-compose.test.yml up
                 # deploy the image
      - run: docker push Fall2017Swe573:$CIRCLE_BRANCH
